### ISSUE TITLE
Generate a new Business Directory plugin from the LSX Starter Plugin

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-business-directory#1]
Create a new Branch and generate a new plugin from the [LSX Starter Plugin](https://github.com/lightspeeddevelopment/lsx-starter-plugin)

###Naming Conventions
**Prefixes**
- lsx_business_directory_
- lsx_bd_
- LSX_BD_PATH
- LSX_BD_URL
- LSX_BD_VERSION

**Namespacing**
- \lsx\business_directory\
- \lsx\business_directory\classes
- \lsx\business_directory\includes\functions
- \lsx\business_directory\includes\helpers

The plugin should be able to activate with no issues.  We will do the post type registering etc in another issue.

**Comment by jlaguma** [comment]
Pull request for this enhancement: https://github.com/lightspeeddevelopment/lsx-business-directory/pull/12
