### ISSUE TITLE
Create 2 new business email notifications

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-business-directory#18]
### Problem
The user needs to be notified via email when their business has been added / edited or deleted.   In future we might have several users managing a business.

### Solution
Extend the WooCommerce Mails and create the 3 new classes. These will trigger when the relevant action is triggered.

### Designs (to be linked)
- [ ] [New Business Added](https://projects.invisionapp.com/d/main#/console/19153622/406988339/preview)
- [ ] [Business Edited](https://projects.invisionapp.com/d/main#/console/19153622/406988338/preview)
- [ ] [Business Deleted](https://projects.invisionapp.com/d/main#/console/19153622/406988337/preview)

### Additional context
There is a good tutorial on creating a new custom WooCommerce Email [here](https://www.ibenic.com/create-custom-woocommerce-email/).

**Comment by deonschreiber** [comment]
@krugazul @jlaguma I've updated the links to the designs for the relevant emails. We may still need to refine the exact wording for each email

**Comment by krugazul** [comment]
We are not adding in the email for this,  the order table has the listing assigned to it.
