### ISSUE TITLE
Register the post types and taxonomies

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-business-directory#2]
Please register the following post types and the taxonomies.

Post Type - Business Directory
- ID = lsx-business-directory
- Archive Slug = business-directory
- Single Slug = businesses
- Menu Label / Plural Label = Business Directory

Taxonomy - Industry
- ID = lsx-bd-industry
- Single Slug = industry/{term_name}
- Menu Label / Single Label = Industry
- Plural Label =  Industries

Taxonomy - Region
- ID = lsx-bd-region
- Single Slug = region/{term_name}
- Menu Label / Single Label = Region
- Plural Label =  Regions

**Comment by jlaguma** [comment]
Pull request for this enhancement: https://github.com/lightspeeddevelopment/lsx-business-directory/pull/13
