### ISSUE TITLE
When selecting and enquiry form, the button does not show on the single listing

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-business-directory#27]
### Describe the bug
The form has been selected via the settings, but the button and modal do not show

### Steps to Reproduce
1. Go to a single [listing](https://lsx-business-directory.lsdev.biz/business/lightspeed-apex/)
2. See error, no button

### Expected behavior
A button should show with the `btn-primary` class, and when click should open up a bootstrap modal with that form.

### Screenshots
![Screenshot 2020-03-11 at 22 11 03](https://user-images.githubusercontent.com/1805603/76459738-62889400-63e5-11ea-8a76-a6fd6d0a6a51.png)

**Comment by jlaguma** [comment]
Pull request for this bug: https://github.com/lightspeeddevelopment/lsx-business-directory/pull/38
