### ISSUE TITLE
Include the CMB2 as a vendor and register the custom fields

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-business-directory#3]
Please include the CMB2 as a vendor and register the custom fields for the business directory post type.

Images
- Featured Image = Logo
- Banner Image = Directory Banner
- Banner Colour = Default Colour if no banner

**Custom Fields**
Branches (repeatable group)
- Name
- Telephone
- Email
- Website
- Google Place Search.

Address
- Google Maps Search
- Complex Name / Business Park / Street Number
- Street Name
- Suburb
- City
- Postal Code
- State / Province
- Country

Contact
- Primary Email
- Secondary Email
- Primary Phone
- Secondary Phone
- Fax Number
- Website

**Comment by jlaguma** [comment]
Pull request for this enhancement: https://github.com/lightspeeddevelopment/lsx-business-directory/pull/14
