### ISSUE TITLE
Create a new plugin setting box for the post type archive settings

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-business-directory#5]
Create a new settings panel which will house the following fields. The bold titles can be headings if possible.   But i think adding a "title" create a new box.    In that case do 2 boxes.  Because the search settings should not show if LSX Search is disabled.

**General**
- Layout option  (radio buttons  Grid vs List)

**Business Directory - Search*
- Enable Search (checkbox)
- Layout (select)
- Collapse (checkbox)
- Disable Sorting (checkbox)
- Disable the date option (checkbox)
- Display Result Count (checkbox)
- Display Clear Button (checkbox)
- All the Facets listed as checkboxes. (Could we make this group sortable?)

**Comment by jlaguma** [comment]
Pull request for this enhancement: https://github.com/lightspeeddevelopment/lsx-business-directory/pull/16
