### ISSUE TITLE
Verify the default and search  grid and list layouts work on the post type archive

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-business-directory#7]
After generating the plugin you should have already renamed the templates in the plugin as well as making sure the post type archive is displaying and using the correct template.

You will need to look at the design and make sure all of the relevant fields are being called through,  as well as the search filters from #6 are displaying and the options are working.

[Directory Grid Layout](https://projects.invisionapp.com/d/main#/console/19153622/403917535/preview)
[Directory List Layout](https://projects.invisionapp.com/d/main#/console/19153622/403917536/preview)

**Testing**
- [ ] The grid and list layout should just fill the content area if LSX search is disabled.  So all the search elements should be hidden, and the banner title says Business Directory 
- [ ] The page should be able to sort and page using the facets.
- [ ] As well as the facets working and filtering the page.

**Comment by jlaguma** [comment]
Pull request for this enhancement: https://github.com/lightspeeddevelopment/lsx-business-directory/pull/22
