### ISSUE TITLE
Banners generated by this plugin are using block classes

### ISSUE THREAD

**Issue by viscosho** [lightspeeddevelopment/lsx-business-directory#73]
### Describe the bug
Banners generated by this plugin are using block classes.
- For most banners for dynamic pages the html use is from a block, this should not be like this, it should use LSX classes, block classes do not work outside a block.
They are coming from the `do_banner` function on this plugin.
Please change the structure to be like an LSX default banner with LSX classes.

### Expected behavior
Banners autogenerated by the plugin should use LSX classes.

### Screenshots
<img width="464" alt="Screen Shot 2020-03-31 at 11 20 45 AM" src="https://user-images.githubusercontent.com/3129483/78037326-c4cc1900-7341-11ea-8b24-493c1a6d7d2a.png">

**Comment by krugazul** [comment]
@viscosho this was coded this way to mimic a WP Cover block, set as a banner as we use it.  Eventually when the entire page becomes compatible with WP Blocks,  we will be able to disable the code, and allow the use of cover blocks,  with no styling tweaks needed.    As it is already styled to handle a cover block.

Another reason is to keep consistency with pages that are using cover blocks already.

The [terms and conditions](urlhttps://lsx-business-directory.lsdev.biz/terms-conditions/) page using a WP Cover block.
![Screenshot 2020-04-01 at 17 12 56](https://user-images.githubusercontent.com/1805603/78154471-97b06100-743c-11ea-949e-7c58d377a7ef.png)

The listings archive using a banner mimicking the block.
![Screenshot 2020-04-01 at 17 12 24](https://user-images.githubusercontent.com/1805603/78154721-e0681a00-743c-11ea-9e47-b6089b456f8d.png)

**Comment by viscosho** [comment]
Closing this issue, I understand why the banners are built like this so there is no need to do any changes.
