### ISSUE TITLE
Verify the grid and list layouts are working on the taxonomy archives

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-business-directory#8]
After generating the plugin you should have already renamed the templates in the plugin as well as making sure the post type archive is displaying and using the correct template.  This is the same as #7

The taxonomy templates
[Directory Grid Layout](https://projects.invisionapp.com/d/main#/console/19153622/403917535/preview)
[Directory List Layout](https://projects.invisionapp.com/d/main#/console/19153622/403917536/preview)

**Testing**
- [x] The grid and list layout should just fill the content area if LSX search is disabled.  So all the search elements should be hidden, and the banner title says Business Directory 
- [x] The page should be able to sort and page using the facets.
- [x] As well as the facets working and filtering the page.
- [x] While on the taxonomy page,  no facet should show using that taxonomy. e.g   On the “Western Cape '' region archive,  we don't want the “Regions” filters to show.

**Comment by jlaguma** [comment]
Pull request for this enhancement: https://github.com/lightspeeddevelopment/lsx-business-directory/pull/31
