### ISSUE TITLE
Verify the single template works, and pull through the new custom fields

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-business-directory#9]
You will need to make sure the name and slug changes you did for the initial build are working.  And then please take a look at the design and pull through the custom fields to the frontend.  As well as the other information.

[Single Design](https://projects.invisionapp.com/d/main#/console/19153622/403917534/preview)
- [x] All custom fields to be filled in, and pulled through to the frontend
- [ ] One business should be added with just a title and description,  so we can see how the page reacts to the empty elements.

**Comment by krugazul** [comment]
@jlaguma   here are 2 links to help with the [Skype](https://blogs.skype.com/tips/2014/02/05/add-a-skype-call-to-action-to-your-website-or-email-signature/) and the [WhatsApp](https://faq.whatsapp.com/en/26000030/) fields.

**Comment by jlaguma** [comment]
Pull request for this enhancement: https://github.com/lightspeeddevelopment/lsx-business-directory/pull/21

**Comment by krugazul** [comment]
@jlaguma ive tested this here, we still need to do styling - https://lsx-business-directory.lsdev.biz/business/lightspeed-development/
